title: Your Name
description: A clean, silk‑inspired personal site
remote_theme: yaoyao-liu/minimal-light   # Minimal Light is simple & elegant&#8203;:contentReference[oaicite:0]{index=0}
font: "Sans Serif"                       # Switch to a modern sans‑serif base
enable_footnote: false
auto_dark_mode: false
