title: "Moments That Matter"
description: "A minimalist theme inspired by a modern, clean design."
baseurl: "" # e.g. /blog if your site is at example.com/blog
url: ""      # e.g. https://example.com
theme: null  # We are creating our own theme in this folder

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# If you want to generate categories/tags, you can add config here:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
